### ISSUE TITLE
[BUG] timetable.txt

### ISSUE THREAD

**Issue by actuallyaryaman** [CartelProject/VITable-CLI#11]
### Description

can't import timetable.txt in the software successfully
question: do i need to copy the complete timetable from vtop or certain columns?

### Screenshots

![image](https://user-images.githubusercontent.com/72538446/155324905-95bcc34b-9122-4c7a-baac-c76ae86aaded.png)

### Docs

- [X] I have went through the project's README file

**Comment by ersascape** [comment]
Internal Server Error can happen whence there are courses in your timetable that are not present in our public data. 
Consider checking our our API repo and add your classes there, and you can manually run the API and test it out via Swagger.
