### ISSUE TITLE
[FEATURE] Uninstall option

### ISSUE THREAD

**Issue by keri-prog** [CartelProject/VITable-CLI#12]
### Detailed description

I just a need to delete vitable. I currently don't have it installed because of a system update but I get the following error message. How can I remove it?

prompt_vitable:1: command not found: vitable 

Please make it easy to uninstall it.

### Context

It was nice using it but I don't need it right now but there is no uninstall option available.

### Docs

- [X] I have went through the project's README file

**Comment by ersascape** [comment]
Seems like VITable is already uninstalled.
Delete the prompt function from powerlevel10k config and that should go away.
