### ISSUE TITLE
[FEATURE] '25 Courses - Need Contributions

### ISSUE THREAD

**Issue by ersascape** [CartelProject/VITable-CLI#9]
### Detailed description

Add '25 courses to the API

### Context

'25 batch students can use this exec for their classes as well

### Possible implementation

Refer to the API and check if your course is not present

If it isn't, add it as such - 

"CourseNumber": "CourseName"

to the JSON in the API

### Docs

- [X] I have went through the project's README file

**Comment by VisheshBansal** [comment]
Add slots in the [backend repo](https://github.com/CartelProject/VITable-backend)
